name: tujuhcahaya_wprs
description: "7C Flutter Radio WordPress - Hybrid Media Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.1
  flutter_lucide: ^1.7.0
  bloc: ^9.1.0
  dartz: ^0.10.1
  get_it: ^9.1.0
  freezed_annotation: ^3.1.0
  equatable: ^2.0.7
  lottie: ^3.3.2

  dio: ^5.0.3
  connectivity_plus: ^7.0.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  sqflite: ^2.3.0
  path_provider: ^2.0.9
  path: ^1.8.1

  adaptive_theme: ^3.4.1
  easy_localization: ^3.0.2

  firebase_core: ^4.2.1
  onesignal_flutter: ^5.2.1

  radio_player: ^2.2.1
  volume_regulator: ^2.4.2

  cached_network_image: ^3.2.0
  flutter_cache_manager: ^3.4.1
  url_launcher: ^6.2.0
  flutter_html: ^3.0.0-beta.2

  material_color_utilities: ^0.13.0
  rxdart: ^0.27.7
  flutter_avif: ^3.1.0
  share_plus: ^12.0.1

dependency_overrides:
  material_color_utilities: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  freezed: ^3.2.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/images/user_levels/
    - assets/animations/
    - assets/others/
    - assets/sprites/
    - assets/sprites/backgrounds/
    - assets/sprites/game_level_listening/
    - assets/sprites/eggs/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
